version: '3'

services:
  basic_config_master:
    build: ./basic_config_master
    container_name: basic_config_master
    command: /usr/sbin/init
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /var/run/docker.sock:/var/run/docker.sock
      - ../simple_grid_puppet_module/:/simple_grid
      - ./basic_config_master/data:/data
      - ../simple_grid_infra_validation_engine:/etc/simple_grid/testinfra/simple_grid_infra_validation_engine
      - ../simple_grid_yaml_compiler:/etc/simple_grid/testinfra/simple_grid_yaml_compiler
    networks:
      simple:
        ipv4_address: 192.168.1.2
        aliases:
          - basic_config_master.cern.ch
          - lightweight_component01:basic_config_master.cern.ch
          - lightweight_component02:basic_config_master.cern.ch
  
  lightweight_component01:
    build: ./lightweight_component
    container_name: lightweight_component01
    command: /usr/sbin/init
    environment:
      - NAME=lightweight_component01
    # cgroup_parent: lightweight_component_cgroup
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - ./lightweight_component/data/:/data 
      - ../simple_grid_puppet_module/:/simple_grid
      # - ../tmp/lightweight_component01:/var/lib/docker   
    networks:
      simple:
        ipv4_address: 192.168.1.4
        aliases:
          - lightweight_component01.cern.ch
          - config_master:lightweight_component01.cern.ch
          - basic_config_master:lightweight_component01.cern.ch
          - lightweight_component02:lightweight_component01.cern.ch
  
  lightweight_component02:
    build: ./lightweight_component
    container_name: lightweight_component02
    command: /usr/sbin/init
    environment:
      - NAME=lightweight_component02
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - ./lightweight_component/data/:/data 
      - ../simple_grid_puppet_module/:/simple_grid  
    networks:
      simple:
        ipv4_address: 192.168.1.5
        aliases:
          - lightweight_component02.cern.ch
          - lightweight_component01:lightweight_component02.cern.ch
          - config_master:lightweight_component02.cern.ch
          - basic_config_master:lightweight_component02.cern.ch
networks:
  simple:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24


    
    
